-- 20260424170000_performance_unused_index_cleanup_batch5.sql
-- Objectif : suppression de tous les unused_index restants (81), batch unique, full clean

DO $$
DECLARE
    rec RECORD;
BEGIN
    -- Liste générée automatiquement à partir des lints advisors
    FOR rec IN SELECT unnest(ARRAY[
        'construction_phases_created_by_idx',
        'construction_phases_zone_idx',
        'construction_phases_subcontractor_idx',
        'worker_qualifications_subcontractor_idx',
        'supply_orders_zone_idx',
        'supply_orders_subcontractor_idx',
        'equipment_bookings_zone_idx',
        'equipment_bookings_subcontractor_idx',
        'site_journal_entries_zone_idx',
        'site_journal_entries_subcontractor_idx',
        'fkidx_audit_log_9aebc791',
        'fkidx_budgets_15a897eb',
        'fkidx_document_versions_3e2f8bb6',
        'fkidx_documents_f753a225',
        'fkidx_documents_fea38feb',
        'fkidx_equipment_bookings_632e449c',
        'fkidx_expenses_89c2921d',
        'fkidx_expenses_b73dfc37',
        'fkidx_key_results_61136fec',
        'fkidx_recurrent_tasks_ea031be5',
        'fkidx_milestones_a1f38c8f',
        'fkidx_notifications_fd8fe19e',
        'fkidx_notifications_1867a058',
        'fkidx_objectives_5e1728e3',
        'fkidx_objectives_2f3a7968',
        'fkidx_profiles_903af259',
        'fkidx_project_baselines_d7fc3f17',
        'fkidx_project_invitations_f78ab2dc',
        'fkidx_project_invitations_f3e6159b',
        'fkidx_project_permissions_d183bae4',
        'fkidx_project_subcontractors_37ddbe11',
        'fkidx_projects_842e84fb',
        'fkidx_resource_permissions_13ded459',
        'fkidx_risk_register_d904d5bc',
        'fkidx_safety_checklist_items_538fcf69',
        'fkidx_site_incidents_f44f7795',
        'fkidx_site_incidents_d4c73701',
        'fkidx_site_journal_entries_6ba8faff',
        'fkidx_site_photos_0c3f0716',
        'fkidx_site_zones_790ceba6',
        'fkidx_site_zones_d0363141',
        'fkidx_sla_rules_036b2d7e',
        'fkidx_sla_violations_44f4e768',
        'fkidx_subtasks_1f3bf0b7',
        'fkidx_supply_orders_900447f4',
        'fkidx_tasks_5cf926a3',
        'fkidx_tasks_81971ae1',
        'fkidx_virtual_members_df8997d8',
        'fkidx_worker_qualifications_5c06a866',
        'comment_reactions_user_id_fk_idx',
        'project_members_user_id_fk_idx',
        'team_capacity_user_id_fk_idx',
        'idx_task_assignees_user_id',
        'automation_rules_project_idx',
        'decision_journal_project_idx',
        'milestones_project_idx',
        'project_baselines_project_idx',
        'tasks_project_id_idx',
        'tasks_parent_id_idx',
        'expenses_project_id_idx',
        'virtual_members_project_id_idx',
        'site_zones_project_idx',
        'project_subcontractors_project_idx',
        'worker_qualifications_project_idx',
        'safety_checklist_project_idx',
        'supply_orders_project_idx',
        'equipment_bookings_project_idx',
        'site_journal_entries_project_idx',
        'site_incidents_project_idx',
        'site_incidents_zone_idx',
        'site_incidents_subcontractor_idx',
        'resource_permissions_resource_idx',
        'comments_task_id_idx',
        'time_entries_task_id_idx',
        'task_templates_project_idx',
        'task_dependencies_target_idx',
        'risk_register_project_idx',
        'document_versions_document_idx',
        'sla_rules_project_idx',
        'sla_violations_rule_idx',
        'task_milestone_mapping_milestone_idx'
    ]) AS idxname
    LOOP
        EXECUTE format('DROP INDEX IF EXISTS public.%I;', rec.idxname);
    END LOOP;
END $$;
